### PR TITLE
updated dependencies

### PR DESCRIPTION
**Pull request by asiFarran**

### CODE REVIEW

**Review by SylvainEstevez — APPROVED** [review]

**Comment by asiFarran** [comment]
@SylvainEstevez I cant merge this. Could you kindly do that.
Also, I dont think I can publish this to the registry right ? I never published anything to NPM before but I suspect I need to have some permissions to do so ...

**Comment by SylvainEstevez** [comment]
@asiFarran I invited you to be admin on both the GH and NPM orgs, check you inbox

**Comment by asiFarran** [comment]
Got it and accepted invites. I still dont seem to have write access to this repo though - cannot merge it

**Comment by SylvainEstevez** [comment]
I made you owner, try again @asiFarran ?

**Pull request merged**
